default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOSTNAME'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['DATABASE_DEV_NAME'] %>
test:
  <<: *default
  database: <%= ENV['DATABASE_TEST_NAME'] %>
production:
  <<: *default
  database: <%= ENV['DATABASE_PROD_NAME'] %>
